services:
  - type: web
    name: ai-article-summarizer
    env: python
    buildCommand: pip install -r requirements.txt && python -m textblob.download_corpora
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0